#pragma once
enum ENEMY_ANIMATION_STATES
{
	ENEMY_IDLE = 0,
	ENEMY_MOVING,
	ENEMY_MOVING_DOWN,
	ENEMY_JUMPING,
	ENEMY_FALLING,
	ENEMY_ATTENTION,
	ENEMY_SHOT,
	ENEMY_SLEEP,
	ENEMY_BITE,
	ENEMY_DEATH,
	ENEMY_TAKING_DAMAGE,
	ENEMY_RUN,
	ENEMY_TELEPORT,
	ENEMY_PUNCH,
	ENEMY_DOUBLE_KICK,
	ENEMY_HOWL,
	ENEMY_HIT_EARTH,
	ENEMY_AWAKENING
};