#pragma once
enum class RED_MUTANT_STATE
{
	RED_MUTANT_IDLE = 0,
	RED_MUTANT_MOVING,
	RED_MUTANT_JUMPING,
	RED_MUTANT_SHOT,
	RED_MUTANT_DEATH,
	RED_MUTANT_TAKING_DAMAGE,
	RED_MUTANT_RUN,
	RED_MUTANT_ATTACKING,
	RED_MUTANT_TELEPORT
};